plugins {
    id 'com.android.application'
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.ByteMechanics.matscape"
        minSdk 29
        targetSdk 36
        versionCode 6
        versionName "1.0"

        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def variantName = variant.name
            if (output.outputFileName != null && output.outputFileName.toString().endsWith('.apk')) {
                output.outputFileName = "app-${variantName}.apk"
            }
        }
    }

    signingConfigs {
        release {
            def localProps = new Properties()
            def localPropsFile = rootProject.file("local.properties")
            if (localPropsFile.exists()) {
                localProps.load(localPropsFile.newDataInputStream())
            }

            def getEnvOrLocalProp = { key ->
                System.getenv(key) ?: localProps.getProperty(key)
            }

            def keystorePath = getEnvOrLocalProp("RELEASE_KEYSTORE_PATH") ?: file("./keystore.jks")
            if (keystorePath != null) {
                storeFile file(keystorePath)
                storePassword getEnvOrLocalProp("RELEASE_STORE_PASSWORD")
                keyAlias getEnvOrLocalProp("RELEASE_KEY_ALIAS")
                keyPassword getEnvOrLocalProp("RELEASE_KEY_PASSWORD")
            } else {
                println("⚠️ RELEASE_KEYSTORE_PATH is missing — skipping release signing")
            }
        }
    }

    buildTypes {
        debug {
            versionNameSuffix "-debug"
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.ByteMechanics.matscape'
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}